version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  backend:
    build: .
    environment:
      DB_HOST : db
      DB_NAME : votes
      DB_USER : postgres
      DB_PASSWORD : postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
  


